sudo: required
services:
    - docker

before_install:
    - docker build -t samarthhegde/docker-react -f Dockerfile.dev .

script:
    - docker run samarthhegde/docker-react npm run test -- --coverage